### ISSUE TITLE
Error requiring python.

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/bootstrap-script#1]
I spun up a fresh version of a digital ocean instance with the default ubuntu and ran the bootstrap.  I got an error requiring python. Is this something you have seen before and is it something that would be worth fixing for this project?

```bash
checking for python >= 2.5... ./configure: line 12390: -c: command not found
./configure: line 12394: test: : integer expression expected
not found
configure: error: found python  (); required >= 2.5
See `config.log' for more details.
```

**Comment by RX14** [comment]
Do you have python 2 installed?

**Comment by wontruefree** [comment]
I did it manually.  I was just letting you know for instances that do not come with python preinstalled.  I think the default Ubuntu images do not come with it preinstalled.

**Comment by RX14** [comment]
If I ever get around to writing a README it'll be there
